FROM jpts/sectools:full

RUN apk add --no-cache vim openssh \
 && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
 && sed -i s/#AllowTcpForwarding.*/AllowTcpForwarding\ yes/ /etc/ssh/sshd_config \
 && mkdir -p /var/run/sshd \
 && echo "root:OPaeyoo6aisha1Waiyoo" | chpasswd \
 && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''

EXPOSE 3456
CMD ["/usr/sbin/sshd", "-D", "-p", "3456", "-e"]
