FROM docker.io/jpts/sectools:latest

# We use a hardcoded password here, as we may not be able to access one generated at runtime
RUN apk add --no-cache vim openssh \
 && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
 && sed -i s/#AllowTcpForwarding.*/AllowTcpForwarding\ yes/ /etc/ssh/sshd_config \
 && mkdir -p /var/run/sshd \
 && echo "root:OPaeyoo6aisha1Waiyoo" | chpasswd 

EXPOSE 3456
CMD ["/usr/sbin/sshd", "-D", "-p", "3456", "-e"]
